const ehfCheck = require('./index');

test("Check that 958381492 / Akershus Fylkeskommune can receive EHF", async () => {
  const res = await ehfCheck("921693230");
  expect(res).toEqual({
    EHF_POSTAWARD_G3_P06_3_0: "Ja",
    Arkivmelding_TekniskeTjenester: "Nei",
    EHF_ORDER_RESPONSE: "Nei",
    EHF_POSTAWARD_G3_P02_3_0_EO: "Nei",
    PRACC_ESENS_P001_EO: "Nei",
    PEPPOLBIS_3_0_ORDERING_EO: "Nei",
    EHF_POSTAWARD_G3_P01_3_0_EO: "Nei",
    EHF_POSTAWARD_G3_P09_3_0_EO: "Nei",
    BIS36_MLR: "Nei",
    PAYMENT_01_RESPONSE_OLD: "Nei",
    PEPPOLBIS_3_0_BILLING_01_UBL_SWEDEN: "Nei",
    Avtalt_avtalt: "Nei",
    EHF_POSTAWARD_G3_P07_3_0: "Nei",
    PAYMENT_10: "Nei",
    PAYMENT_03_RESPONSE_OLD: "Nei",
    PEPPOLBIS_28A_2_0: "Nei",
    PAYMENT_01_OLD: "Nei",
    eInnsyn_Response: "Ja",
    PRACC_ESENS_P002_CA: "Nei",
    identifier: "921693230",
    EHF_CREDITNOTE_2_0: "Nei",
    EHF_ORDER: "Nei",
    PAYMENT_04_RESPONSE: "Nei",
    PEPPOLBIS_28A_2_0_RESPONSE: "Nei",
    BIS01: "Nei",
    PEPPOLBIS_3_0_BILLING_01_UBL: "Ja",
    BIS03: "Nei",
    EHF_ADVORDER_3_0_PILOT_RESPONSE: "Nei",
    PEPPOLBIS_3_0_INVOICE_RESPONSE_EO: "Nei",
    Arkivmelding_Administrasjon: "Nei",
    Arkivmelding_HelseSosialOgOmsorg: "Nei",
    PAYMENT_02_OLD: "Nei",
    PAYMENT_10_RESPONSE: "Nei",
    EHF_30A_1_0: "Nei",
    EHF_POSTAWARD_G3_P05_3_0: "Nei",
    EHF_XYA_1_0_REMINDER: "Nei",
    BIS06: "Nei",
    ISO20022_Pain_001: "Nei",
    PEPPOLBIS_3_0_ORDER_ONLY_EO: "Nei",
    name: "VIKEN FYLKESKOMMUNE",
    EHF_POSTAWARD_G3_P09_3_0_CA: "Nei",
    PAYMENT_03_RESPONSE: "Nei",
    Digitalpost_Info: "Nei",
    EHF_INVOICE_2_0: "Nei",
    BIS05_V2: "Nei",
    PEPPOLBIS_01A_2_0: "Nei",
    Arkivmelding_KulturIdrettOgFritid: "Nei",
    EHF_POSTAWARD_G3_P01_3_0_CA: "Nei",
    PAYMENT_03_OLD: "Nei",
    PRACC_ESENS_P001_CA: "Nei",
    Arkivmelding_Response: "Nei",
    PRACC_ESENS_P003_EO: "Nei",
    EHF_CATALOGUE_RESPONSE: "Nei",
    EHF_INVOICE_CREDITNOTE_2_0: "Nei",
    eInnsyn_Journalpost: "Nei",
    Arkivmelding_NaturOgMiljoe: "Nei",
    PAYMENT_04_OLD: "Nei",
    PEPPOLBIS_3_0_DESPATCH_ADVICE_CA: "Nei",
    Arkivmelding_Naeringsutvikling: "Nei",
    PAYMENT_02_RESPONSE: "Nei",
    PAYMENT_02_RESPONSE_OLD: "Nei",
    PAYMENT_04_RESPONSE_OLD: "Nei",
    PEPPOLBIS_03A_2_0: "Nei",
    PEPPOLBIS_3_0_ORDERING_CA: "Ja",
    EHF_POSTAWARD_G3_P03_3_0: "Nei",
    PEPPOLBIS_3_0_ORDER_AGREEMENT_CA: "Nei",
    eInnsyn_Meeting: "Nei",
    PEPPOLBIS_30A_2_0: "Nei",
    Digitalpost_Vedtak: "Nei",
    BIS04_V2: "Nei",
    PRACC_ESENS_P002_EO: "Nei",
    PAYMENT_10_OLD: "Nei",
    PEPPOLBIS_3_0_BILLING_01_CII: "Nei",
    Arkivmelding_ByggOgGeodata: "Nei",
    EGOV_GE_1_0_REQUEST: "Nei",
    Arkivmelding_OppvekstOgUtdanning: "Nei",
    EHF_POSTAWARD_G3_P08_3_0: "Nei",
    eInnsyn_Innsynskrav: "Ja",
    Icd: "0192",
    PAYMENT_01_RESPONSE: "Nei",
    PAYMENT_10_RESPONSE_OLD: "Nei",
    PAYMENT_04: "Nei",
    PRACC_ESENS_P003_CA: "Nei",
    EHF_ADVORDER_3_0_PILOT_REQUEST: "Nei",
    PAYMENT_03: "Nei",
    PAYMENT_02: "Nei",
    EGOV_GE_1_0_RESPONSE: "Nei",
    PAYMENT_01: "Nei",
    regdate: "2019.09.30",
    Arkivmelding_TrafikkReiserOgSamferdsel: "Nei",
    Arkivmelding_SkatterOgAvgifter: "Nei",
    EHF_CATALOGUE: "Nei",
    EHF_POSTAWARD_G3_P02_3_0_CA: "Ja"
  });
});

test('Check that 994353136 / Kepp Software cannot receive EHF', async () => {
  const res = await ehfCheck('994353136');
  expect(res).toEqual(false);
});
